### ISSUE TITLE
[Feature request] MySQL database support

### ISSUE THREAD

**Issue by Hybrid512** [Wintermute0110/plugin.program.AEL#136]
Kodi is not really "client/server" focused but at least, it can handle central database through MySQL for Videos and Music.
It is far from perfect but at least, it is usable.
Could AEL use the same approach for games ?
Basically use MySQL as a database backend instead of local mysqlite DB ?

Would be great to have a centralized "server" setup with many different "clients".

Regards

**Comment by Wintermute0110** [comment]
It is very unlikely that I will implement such thing in an addon, because of the way addons work in Kodi. Addons are not being in execution all the time. Every time you enter a menu the addon execution starts and finishes. This has a lot of implications about what addons can and cannot do.

In any case, with some organization from your side you can "emulate" this behavior. Suppose you have your ROMs and assets in a NAS, and that you network mount the paths in the different computers where you have Kodi installed. Artwork is always shared between AEL instances because it is in the NAS. Regarding metadata, you can export all the metadata into NFO files which will be next to the ROMs, and other AEL instances can read these NFO files. Note that if you do not use the online scrapers, AEL can scan a launcher with thousands of ROMs in mere seconds. Furthermore, in another directory of the NAS you can keep all the XML configuration files, and if you choose the proper configuration these XML files can be shared among all the Kodi instances.

**Comment by Hybrid512** [comment]
That's mostly what I'm doing, I was just hoping for a less tricky way.

Thx for your answer.
