### ISSUE TITLE
gamepad still controlls kodi when emulator is run

### ISSUE THREAD

**Issue by leissa** [Wintermute0110/plugin.program.AEL#59]
Hi,

I'm running ArchLinux and Kodi from within fluxbox. I created a really simple launcher which just starts retroarch. When controlling retroarch with a gamepad it will also invisibly control kodi which still runs in background - possibly starting movies etc. Note that fixing issue #58 would automatically fix this bug, too.

**Comment by Wintermute0110** [comment]
Some user have reported this issue also. In my setup I use Ubuntu, run Kodi with OpenBox window manager and it works like a charm. I'm not sure if the problem if caused by Fluxbox.

In AEL addon settings you may want to increase the waiting time before/after launching and see if that helps. Also, you can activate the per-launcher setting to put Kodi into windowed mode. Also, if you can try OpenBox instead of Fluxbox that would be great to confirm wheter Fluxbox is responsible or not.
