### ISSUE TITLE
Directory as file extension

### ISSUE THREAD

**Issue by DocMAX** [Wintermute0110/plugin.program.AEL#74]
Hello,

i have an emulator (cemu), which reads from `ROM\ROMNAME\*\code\*.prx`
Now i want to load the games with this "mask".

How can i make AEL read the "ROMNAME" and give it as variable?

Kr,
DocMAX

**Comment by Wintermute0110** [comment]
Can you put an example with actual filenames or point to a tutorial? For example:

```
/home/kodi/ROMs/Super Mario/blablabla_a/code/Mario.prx
/home/kodi/ROMs/Super Mario/blablabla_b/code/Mario.prx
```
I need to understand well how cemu works before thinking of a solution.

**Comment by DocMAX** [comment]
If the Wii U sources are in Loadliine Format then the pattern is like this:

/home/kodi/ROMs/Super Mario/code/aabb.prx
/home/kodi/ROMs/Pokemon/code/yyxx.prx
/home/kodi/ROMs/Boxing/code/ttww.prx

**Comment by Wintermute0110** [comment]
OK, I see. Then, to call the emulator you use:

```
$ cemu -g "Super Mario"
```

or

```
$ cemu -g "/home/kodi/ROMs/Super Mario/code/aabb.prx"
```

**Comment by DocMAX** [comment]
What? The goal is to let AEL scan for directorys and give `"/home/kodi/ROMs/Super Mario/code/aabb.prx"`

**Comment by baka0815** [comment]
@DocMAX so it's the latter.
@Wintermute0110  wanted to know if you need just ``"XXX"`` for the command line or if you'll need the whole string ``"/home/kodi/ROMs/XXX/code/YYY.prx"``.

**Comment by DocMAX** [comment]
@Wintermute0110 the whole path is needed

**Comment by Wintermute0110** [comment]
Thanks @baka0815 for your help.

@DocMAX You should configure your launcher as follows:

 * Executable: the location of your cemu.exe
 * ROM directory: `/home/kodi/ROMs` as in the example
 * ROM extension: prx
 * Arguments: `-g "$rom$"`

In AEL addon settings make sure the `Recursive scan` option is ON.

At launching, AEL will substitute `$rom$` with the filename of each ROM.

Also, you should create NFO files and then populate the metadata. Otherwise, the ROMs will be listed in AEL as `aabb`, `yyxx`, etc. To do this, first scan your launcher. Then, open the launcher context menu, "Manage ROMs", "Export ROMs NFO files". Then, edit the NFO files and change the ROM title. Finally, go to the launcher context menu, "Manage ROMs", "Import ROMs NFO files". Be careful once you edit the NFO files not to overwrite them (or make a backup of your NFO files).
