### ISSUE TITLE
Reference before definition (PythonToCpp) exception while scraping from MobyGames

### ISSUE THREAD

**Issue by treymerkley** [Wintermute0110/plugin.program.AEL#77]
Great stuff with this launcher. I'm running into some issues, but even as a beta app it's head and shoulders above most other HTPC launchers.

I'm getting an exception while trying to scrape, though. I tried playing with this to force reference, but no luck. This is a little more complex than I'm used to.

```
20:26:55.351 T:139870097893120   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'launcher' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/home/user/.kodi/addons/plugin.program.advanced.emulator.launcher/addon.py", line 39, in <module>
                                                main.Main().run_plugin()
                                              File "/home/user/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 305, in run_plugin
                                                self.run_protected(command, args)
                                              File "/home/user/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 400, in run_protected
                                                self._command_edit_rom(args['catID'][0], args['launID'][0], args['romID'][0])
                                              File "/home/user/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 3065, in _command_edit_rom
                                                if launcher['nointro_xml_file']:
                                            UnboundLocalError: local variable 'launcher' referenced before assignment
                                            -->End of Python script error report<--
```

**Comment by Wintermute0110** [comment]
Thanks for reporting and for your interest in AEL. You can also have a look at AML if interested.

I will look into this problem ASAP.

**Comment by billywade** [comment]
@Wintermute0110 thanks! I went with AEL because I use a lot of more modern emulators and applications, like Retroarch and Steam, and I

**Comment by Wintermute0110** [comment]
Do not underestimate MAME as a console/computer emulator, specially for pre-PSX systems :)

In future AEL versions I plan to enhance the AEL/AML interaction. For example, you can use AML powerful filters to tame your huge MAME collection and then easily export your filtered out/favourite ROM lists into AEL to conveniently have all your launchers into one place. No need for duplicate ROMs or assets.

**Comment by baka0815** [comment]
Sorry for being off-topic, but it fits:
Is there a future for AEL when the retro core is added to kodi?

**Comment by billywade** [comment]
@baka0815 are you asking about Libretro being integrated into upstream Kodi and implemented via AEL or added into AEL itself?

**Comment by baka0815** [comment]
I'm just asking what will happen to this project if the retro core is added (in kodi 18).
Will this still offer features which are not in mainline kodi then?

**Comment by billywade** [comment]
Well, for one, Retroarch/libretro is pretty limited in a lot of ways: it can only use whatever cores are available, and some cores are feature incomplete to upstream, so no Steam, Lutris, etc. If Wintermute would want to halt development, that's up to them, but the project would probably still be pretty useful. More likely (to me), I would see this add-on or one like it getting canonized into upstream Kodi, since these sorts of app launchers have been indispensable since XBMC was released. 'Course, I don't know Kodi's vision, since a lot of features (Blu-ray playback) are a matter of just implementing other projects.

**Comment by eggfoo** [comment]
Also. This add on. Allows for other emulators to be used. Wii U/3ds/ps3/switch etc etc. 
also. It allows for arguments to be launched. 

I use AEL with rocket launcher to decompress my larger rom files and have a splash screen for this. It works great.

**Comment by billywade** [comment]
@eggfoo do you mind writing up a guide or linking to how you set up the splash screen and compression? I've been using a small file server for storage and being able to compress and decompress on the fly would make space a little less tight.

**Comment by eggfoo** [comment]
ill post a video of what im using in a few. when i get time. (work, and family drain my free time)

**Comment by billywade** [comment]
I feel that, don't worry about it.

**Comment by Wintermute0110** [comment]
> Is there a future for AEL when the retro core is added to Kodi?

Kodi Leia will include Retroplayer but the implementation is still lacking many things, for example, compressed ROMs are not supported. For Leia I still recommend using Retroarch as an external emulator. Also, Leia won't include the games database. This means that you will browse your games like files in the FileSystem browser, not metadata or artwork whatsoever.

After Leia... nobody knows what's going to happen. Probably Kodi M**** will include a games database but I don't think the core devs will include all AEL features in Kodi. For example, DAT support, 1 game 1 ROM display mode, etc. In any case, I will keep AEL as a general launcher and also to give support to emulator that are not part of Retroarch. I'm not sure if a future version of AEL will be more oriented towards general launching of apps, emulator front-end, etc. that will depend on how Kodi game situation develops.

AML, on the other hand, will have a healthy future in many years to come. The reason is that MAME is so special that I doubt that the core developers will include all the MAME features in the application.

**Comment by billywade** [comment]
@Wintermute0110 We should talk outside of the thread about MAME. Most of what I emulate is post-PSX, but you seem so infatuated I'd like to find out what the hubbub is.

**Comment by Wintermute0110** [comment]
MobyGames scraper fixed.
